server:
  port: 8000


spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      #ddl-auto: none:=

    database-platform:
  datasource:
    platform: postgres
#    url: ${P_URL:jdbc:postgresql://localhost:5432/bookstore}
    url: ${P_URL}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    driverClassName: org.postgresql.Driver

    #    username: webedi
    #    password: 111111


#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/bookstore
#    username: postgres
#    password: admin
#    #    username: webedi
#    #    password: 111111
#    driverClassName: org.postgresql.Driver
