server:
  port: 8000


spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      #ddl-auto: none:=

  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/bookstore
#    url: ${P_URL}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    driverClassName: org.postgresql.Driver
